n1 = float(input('Digite um número: '))
n2 = float(input('Digite outro número: '))
s = (n1+n2)
print('A soma entre ', n1, ' e ', n2, ' é: ', s)
print('A soma entre {} e {} é: {}'.format(n1, n2, s))
